language: generic

deploy:
  provider: s3
  access_key_id: AKIAIFQ6DJAUYXMZ7RSA
  secret_access_key: $AWS_SECRET_KEY
  bucket: lottapleasure.com
  acl: public_read
  on:
    repo: Ninuce/lottapleasure
    branch: master
notifications:
  email: false
