deploy:
  provider: s3
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: vsC56HuNr6qeS33/E7zJ0KQBFJa9BX0pdjqa2QdzEsSkSctSwlL5bWGSAPqQ6ktkrTtkMXMTgn6IpPlptpUdhi/FKPnVApPJu8J0pFEG33SMR5YyGoRG8fDvNbvqYgLQN2sGamKMu5rxQ3/hFovQLQAdePV7IVZ3sGIPFrZGMUz9iV9zT3VTq5RcHh8DxwCMVDc8BF410/wCdEALt/ej++Yx9g2F31sI9q6s5gHPCaIX32Tmb3HGVeZC/s3iqg4NEuQ58dG9MgZRYGpvjeBEnzkOk1eMpuLkZC6O/8Y9aqJz2WQRQbTPK2VvmTNSPKJFr1J+m/WJyDFolo5YNqmdFky2sOb0jkh0Zog75oJkwY/hPmt1mNiPGhmjbAG33NSsw13FAAIP6FP7/M64fr9img/W7b59I9syXe8xFBN+QHgfYjsfkfcXuydNh8cqAx4wn/W96sA1kaAXXpA6qUBOIJ3zRHuXcO6jfKogEmI2BPBFDKuvIFQOSiJ+rLGGDjgzg+ws7b6q4KY9xk80kAT2ReQTaTvdh6LLEbS8Pk+roxTKUNc2ZNHLtBikeZIF0r4oUnNOZU4JLDKRc8TcgiWidJSavwDjNor1tluxIFqFM2GAiieEmKUUKS1O1NRG/rSKLh36YVoK4rmDV3vc746ky3R3MaSib5F5vbeG7yAkdMs=
  bucket: "lottapleasure.com"
  skip_cleanup: true
true:
  branch: master
